In [31]:
import pandas as pd
import numpy as np

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)

## Loading cleaned dataset from Day 1

In [32]:
day1_path = "../data/cleaned_data/APL_Day1_Cleaned.csv"

df_day1 = pd.read_csv(
    day1_path,
    encoding="cp1252",
    low_memory=False
)

print("Day 1 cleaned dataset loaded successfully.")
print("Shape:", df_day1.shape)

Day 1 cleaned dataset loaded successfully.
Shape: (180519, 40)

## Creating Day 2 working copy

In [33]:
df_day2 = df_day1.copy()

print("Day 2 validation copy created.")
print("Shape:", df_day2.shape)

Day 2 validation copy created.
Shape: (180519, 40)

## Validation 1 - Dataset shape

In [34]:
expected_rows = 180519
expected_columns = 40

actual_rows, actual_columns = df_day2.shape

print("Expected rows:", expected_rows)
print("Actual rows:", actual_rows)

print("Expected columns:", expected_columns)
print("Actual columns:", actual_columns)

if (actual_rows == expected_rows) and (actual_columns == expected_columns):
    print("Shape validation: PASS")
else:
    print("Shape validation: CHECK REQUIRED")

Expected rows: 180519
Actual rows: 180519
Expected columns: 40
Actual columns: 40
Shape validation: PASS

## Validation 2 - Columns names

In [35]:
expected_columns = [
    "Type",
    "Days for shipping (real)",
    "Days for shipment (scheduled)",
    "Benefit per order",
    "Sales per customer",
    "Delivery Status",
    "Late_delivery_risk",
    "Category Id",
    "Category Name",
    "Customer City",
    "Customer Country",
    "Customer Fname",
    "Customer Id",
    "Customer Lname",
    "Customer Segment",
    "Customer State",
    "Customer Street",
    "Customer Zipcode",
    "Department Id",
    "Department Name",
    "Latitude",
    "Longitude",
    "Market",
    "Order City",
    "Order Country",
    "Order Customer Id",
    "Order Item Discount",
    "Order Item Discount Rate",
    "Order Item Product Price",
    "Order Item Profit Ratio",
    "Order Item Quantity",
    "Sales",
    "Order Item Total",
    "Order Profit Per Order",
    "Order Region",
    "Order State",
    "Order Status",
    "Product Name",
    "Product Price",
    "Shipping Mode"
]

actual_columns = df_day2.columns.tolist()

missing_columns = set(expected_columns) - set(actual_columns)
unexpected_columns = set(actual_columns) - set(expected_columns)

print("Missing columns:", missing_columns)
print("Unexpected columns:", unexpected_columns)

if not missing_columns and not unexpected_columns:
    print("Column validation: PASS")
else:
    print("Column validation: CHECK REQUIRED")

Missing columns: set()
Unexpected columns: set()
Column validation: PASS

## Validation 3 - Missing values

In [36]:
missing_values = df_day2.isnull().sum()

missing_summary = (
    missing_values[missing_values > 0]
    .sort_values(ascending=False)
)

display(missing_summary)

if missing_summary.empty:
    print("Missing value validation: PASS")
else:
    print("Missing value validation: CHECK REQUIRED")

Series([], dtype: int64)

Missing value validation: PASS

## Validation 4 - Duplicate values

In [37]:
duplicate_count = df_day2.duplicated().sum()

print("Duplicate rows:", duplicate_count)

if duplicate_count == 0:
    print("Duplicate validation: PASS")
else:
    print("Duplicate validation: CHECK REQUIRED")

Duplicate rows: 0
Duplicate validation: PASS

## Validation 5 - Data types

In [38]:
dtype_summary = pd.DataFrame({
    "Column": df_day2.columns,
    "Data_Type": df_day2.dtypes.astype(str).values
})

display(dtype_summary)

                           Column Data_Type
0                            Type       str
1        Days for shipping (real)     int64
2   Days for shipment (scheduled)     int64
3               Benefit per order   float64
4              Sales per customer   float64
5                 Delivery Status       str
6              Late_delivery_risk     int64
7                     Category Id     int64
8                   Category Name       str
9                   Customer City       str
10               Customer Country       str
11                 Customer Fname       str
12                    Customer Id     int64
13                 Customer Lname       str
14               Customer Segment       str
15                 Customer State       str
16                Customer Street       str
17               Customer Zipcode       str
18                  Department Id     int64
19                Department Name       str
20                       Latitude   float64
21                      Longitude   float64
22                         Market       str
23                     Order City       str
24                  Order Country       str
25              Order Customer Id     int64
26            Order Item Discount   float64
27       Order Item Discount Rate   float64
28       Order Item Product Price   float64
29        Order Item Profit Ratio   float64
30            Order Item Quantity     int64
31                          Sales   float64
32               Order Item Total   float64
33         Order Profit Per Order   float64
34                   Order Region       str
35                    Order State       str
36                   Order Status       str
37                   Product Name       str
38                  Product Price   float64
39                  Shipping Mode       str

## Validation 6 - Categorical vlaues

In [39]:
categorical_columns = [
    "Type",
    "Delivery Status",
    "Customer Segment",
    "Market",
    "Order Status",
    "Shipping Mode"
]

for col in categorical_columns:
    print("\n" + "=" * 60)
    print(col)
    print("=" * 60)
    print(df_day2[col].value_counts())

============================================================
Type
============================================================
Type
DEBIT       69295
TRANSFER    49883
PAYMENT     41725
CASH        19616
Name: count, dtype: int64

============================================================
Delivery Status
============================================================
Delivery Status
Late delivery        98977
Advance shipping     41592
Shipping on time     32196
Shipping canceled     7754
Name: count, dtype: int64

============================================================
Customer Segment
============================================================
Customer Segment
Consumer       93504
Corporate      54789
Home Office    32226
Name: count, dtype: int64

============================================================
Market
============================================================
Market
LATAM           51594
Europe          50252
Pacific Asia    41260
USCA            25799
Africa          11614
Name: count, dtype: int64

============================================================
Order Status
============================================================
Order Status
COMPLETE           59491
PENDING_PAYMENT    39832
PROCESSING         21902
PENDING            20227
CLOSED             19616
ON_HOLD             9804
SUSPECTED_FRAUD     4062
CANCELED            3692
PAYMENT_REVIEW      1893
Name: count, dtype: int64

============================================================
Shipping Mode
============================================================
Shipping Mode
Standard Class    107752
Second Class       35216
First Class        27814
Same Day            9737
Name: count, dtype: int64

## Validation 7 - Late delivery risk

In [40]:
valid_risk_values = {0, 1}

actual_risk_values = set(
    df_day2["Late_delivery_risk"].dropna().unique()
)

print("Actual values:", actual_risk_values)

if actual_risk_values.issubset(valid_risk_values):
    print("Late_delivery_risk validation: PASS")
else:
    print("Late_delivery_risk validation: CHECK REQUIRED")

Actual values: {np.int64(0), np.int64(1)}
Late_delivery_risk validation: PASS

## Validation 8 - Shipping days

In [41]:
shipping_columns = [
    "Days for shipping (real)",
    "Days for shipment (scheduled)"
]

for col in shipping_columns:
    print("\n", col)
    print(sorted(df_day2[col].dropna().unique()))

 Days for shipping (real)
[np.int64(0), np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5), np.int64(6)]

 Days for shipment (scheduled)
[np.int64(0), np.int64(1), np.int64(2), np.int64(4)]

In [42]:
valid_real_days = set(range(0, 7))
valid_scheduled_days = {0, 1, 2, 4}

actual_real_days = set(
    df_day2["Days for shipping (real)"].dropna().unique()
)

actual_scheduled_days = set(
    df_day2["Days for shipment (scheduled)"].dropna().unique()
)

print(
    "Real shipping days:",
    actual_real_days.issubset(valid_real_days)
)

print(
    "Scheduled shipping days:",
    actual_scheduled_days.issubset(valid_scheduled_days)
)

Real shipping days: True
Scheduled shipping days: True

## Validation 9 - Delivery logic

In [43]:
expected_late = (
    (df_day2["Days for shipping (real)"] >
     df_day2["Days for shipment (scheduled)"])
    & (df_day2["Delivery Status"] != "Shipping canceled")
)

actual_late = df_day2["Delivery Status"] == "Late delivery"

logic_mismatch = df_day2[expected_late != actual_late]

print("Expected late deliveries:", expected_late.sum())
print("Actual late deliveries:", actual_late.sum())
print("Delivery logic mismatches:", len(logic_mismatch))

Expected late deliveries: 98977
Actual late deliveries: 98977
Delivery logic mismatches: 0

In [44]:
display(
    logic_mismatch[
        [
            "Days for shipping (real)",
            "Days for shipment (scheduled)",
            "Delivery Status",
            "Late_delivery_risk"
        ]
    ].head(20)
)

Empty DataFrame
Columns: [Days for shipping (real), Days for shipment (scheduled), Delivery Status, Late_delivery_risk]
Index: []

## Validation 10 - Late risk vs delivery status

In [45]:
risk_mismatch = df_day2[
    (
        (df_day2["Delivery Status"] == "Late delivery") &
        (df_day2["Late_delivery_risk"] != 1)
    )
    |
    (
        (df_day2["Delivery Status"] != "Late delivery") &
        (df_day2["Late_delivery_risk"] != 0)
    )
]

print("Risk/status mismatches:", len(risk_mismatch))

Risk/status mismatches: 0

## Validation 11 - Numeric range check

In [46]:
numeric_columns = df_day2.select_dtypes(
    include=["int64", "float64"]
).columns

numeric_summary = df_day2[numeric_columns].describe().T

display(numeric_summary)

,count,mean,std,min,25%,50%,75%,max
Days for shipping (real),180519.0,3.497654,1.623722,0.000000,2.000000,3.000000,5.000000,6.000000
Days for shipment (scheduled),180519.0,2.931847,1.374449,0.000000,2.000000,4.000000,4.000000,4.000000
Benefit per order,180519.0,21.974989,104.433526,-4274.980000,7.000000,31.520000,64.800000,911.800000
Sales per customer,180519.0,183.107607,120.043668,7.490000,104.380000,163.990000,247.400000,1939.990000
Late_delivery_risk,180519.0,0.548291,0.497664,0.000000,0.000000,1.000000,1.000000,1.000000
Category Id,180519.0,31.851451,15.640064,2.000000,18.000000,29.000000,45.000000,76.000000
Customer Id,180519.0,6691.379495,4162.918106,1.000000,3258.500000,6457.000000,9779.000000,20757.000000
Department Id,180519.0,5.443460,1.629246,2.000000,4.000000,5.000000,7.000000,12.000000
Latitude,180519.0,29.719955,9.813646,-33.937553,18.265432,33.144863,39.279617,48.781933
Longitude,180519.0,-84.915675,21.433241,-158.025986,-98.446312,-76.847908,-66.370583,115.263077
Order Customer Id,180519.0,6691.379495,4162.918106,1.000000,3258.500000,6457.000000,9779.000000,20757.000000
Order Item Discount,180519.0,20.664741,21.800901,0.000000,5.400000,14.000000,29.990000,500.000000
Order Item Discount Rate,180519.0,0.101668,0.070415,0.000000,0.040000,0.100000,0.160000,0.250000
Order Item Product Price,180519.0,141.232547,139.732489,9.990000,50.000000,59.990000,199.990000,1999.990000
Order Item Profit Ratio,180519.0,0.120647,0.466796,-2.750000,0.080000,0.270000,0.360000,0.500000
Order Item Quantity,180519.0,2.127638,1.453451,1.000000,1.000000,1.000000,3.000000,5.000000
Sales,180519.0,203.772092,132.273075,9.990000,119.980000,199.920000,299.950000,1999.990000
Order Item Total,180519.0,183.107607,120.043668,7.490000,104.380000,163.990000,247.400000,1939.990000
Order Profit Per Order,180519.0,21.974989,104.433526,-4274.980000,7.000000,31.520000,64.800000,911.800000
Product Price,180519.0,141.232547,139.732489,9.990000,50.000000,59.990000,199.990000,1999.990000

### Quantity

In [47]:
print(
    "Invalid quantities:",
    (df_day2["Order Item Quantity"] <= 0).sum()
)

Invalid quantities: 0

### Discount rate

In [48]:
print(
    "Invalid discount rates:",
    (
        (df_day2["Order Item Discount Rate"] < 0) |
        (df_day2["Order Item Discount Rate"] > 1)
    ).sum()
)

Invalid discount rates: 0

## Latitude

In [49]:
print(
    "Invalid latitude:",
    (
        (df_day2["Latitude"] < -90) |
        (df_day2["Latitude"] > 90)
    ).sum()
)

Invalid latitude: 0

### Longitude

In [50]:
print(
    "Invalid longitude:",
    (
        (df_day2["Longitude"] < -180) |
        (df_day2["Longitude"] > 180)
    ).sum()
)

Invalid longitude: 0

### Validation 12 - Price consistency

In [51]:
print(
    "Invalid Product Price:",
    (df_day2["Product Price"] <= 0).sum()
)

print(
    "Invalid Order Item Product Price:",
    (df_day2["Order Item Product Price"] <= 0).sum()
)

Invalid Product Price: 0
Invalid Order Item Product Price: 0

## Validation 13 - Financial consistency

In [52]:
financial_columns = [
    "Benefit per order",
    "Sales per customer",
    "Order Item Discount",
    "Order Item Discount Rate",
    "Order Item Product Price",
    "Order Item Profit Ratio",
    "Sales",
    "Order Item Total",
    "Order Profit Per Order",
    "Product Price"
]

display(df_day2[financial_columns].describe().T)

,count,mean,std,min,25%,50%,75%,max
Benefit per order,180519.0,21.974989,104.433526,-4274.98,7.00,31.52,64.80,911.80
Sales per customer,180519.0,183.107607,120.043668,7.49,104.38,163.99,247.40,1939.99
Order Item Discount,180519.0,20.664741,21.800901,0.00,5.40,14.00,29.99,500.00
Order Item Discount Rate,180519.0,0.101668,0.070415,0.00,0.04,0.10,0.16,0.25
Order Item Product Price,180519.0,141.232547,139.732489,9.99,50.00,59.99,199.99,1999.99
Order Item Profit Ratio,180519.0,0.120647,0.466796,-2.75,0.08,0.27,0.36,0.50
Sales,180519.0,203.772092,132.273075,9.99,119.98,199.92,299.95,1999.99
Order Item Total,180519.0,183.107607,120.043668,7.49,104.38,163.99,247.40,1939.99
Order Profit Per Order,180519.0,21.974989,104.433526,-4274.98,7.00,31.52,64.80,911.80
Product Price,180519.0,141.232547,139.732489,9.99,50.00,59.99,199.99,1999.99

## Validation 14 - ID consistency

In [53]:
id_columns = [
    "Category Id",
    "Customer Id",
    "Department Id",
    "Order Customer Id"
]

for col in id_columns:
    print(
        col,
        "unique values:",
        df_day2[col].nunique(),
        "| missing:",
        df_day2[col].isna().sum()
    )

Category Id unique values: 51 | missing: 0
Customer Id unique values: 20652 | missing: 0
Department Id unique values: 11 | missing: 0
Order Customer Id unique values: 20652 | missing: 0

In [54]:
print(
    "Customer Id < 0:",
    (df_day2["Customer Id"] < 0).sum()
)

print(
    "Category Id <= 0:",
    (df_day2["Category Id"] <= 0).sum()
)

print(
    "Department Id <= 0:",
    (df_day2["Department Id"] <= 0).sum()
)

Customer Id < 0: 0
Category Id <= 0: 0
Department Id <= 0: 0

## Validation 15 - Customer ID relationship

In [55]:
customer_id_mismatch = (
    df_day2["Customer Id"] !=
    df_day2["Order Customer Id"]
).sum()

print(
    "Customer ID mismatches:",
    customer_id_mismatch
)

Customer ID mismatches: 0

## Validation 16 - Text quality

In [56]:
text_columns = df_day2.select_dtypes(
    include=["object", "string"]
).columns

whitespace_issues = {}

for col in text_columns:
    count = (
        df_day2[col].astype("string")
        .str.contains(r"^\s|\s$", regex=True, na=False)
        .sum()
    )

    if count > 0:
        whitespace_issues[col] = count

print("Whitespace issues:")
print(whitespace_issues)

Whitespace issues:
{}

## Creating a Day 2 validation summary

In [57]:
validation_results = {

    "Shape": df_day2.shape == (180519, 40),

    "Missing Values": df_day2.isnull().sum().sum() == 0,

    "Duplicate Rows": df_day2.duplicated().sum() == 0,

    "Required Columns": set(expected_columns) == set(df_day2.columns),

    "Late Delivery Risk": set(
        df_day2["Late_delivery_risk"].dropna().unique()
    ).issubset({0, 1}),

    "Shipping Days": actual_real_days.issubset(valid_real_days),

    "Scheduled Days": actual_scheduled_days.issubset(valid_scheduled_days),

    "Delivery Logic": len(logic_mismatch) == 0,

    "Positive Quantity": (df_day2["Order Item Quantity"] > 0).all(),

    "Valid Latitude": (
        df_day2["Latitude"].between(-90, 90)
    ).all(),

    "Valid Longitude": (
        df_day2["Longitude"].between(-180, 180)
    ).all()
}

validation_report = pd.DataFrame(
    list(validation_results.items()),
    columns=["Validation", "Status"]
)

display(validation_report)

            Validation  Status
0                Shape    True
1       Missing Values    True
2       Duplicate Rows    True
3     Required Columns    True
4   Late Delivery Risk    True
5        Shipping Days    True
6       Scheduled Days    True
7       Delivery Logic    True
8    Positive Quantity    True
9       Valid Latitude    True
10     Valid Longitude    True

## Overall Day 2 result

In [58]:
if validation_report["Status"].all():
    print("DAY 2 DATA VALIDATION: PASS")
else:
    print("DAY 2 DATA VALIDATION: CHECK REQUIRED")

DAY 2 DATA VALIDATION: PASS

## Saving Day 2 dataset

In [59]:
day2_path = "../data/cleaned_data/APL_Day2_Validated.csv"

df_day2.to_csv(
    day2_path,
    index=False,
    encoding="cp1252"
)

print("Day 2 validated dataset saved successfully.")
print(day2_path)

Day 2 validated dataset saved successfully.
../data/cleaned_data/APL_Day2_Validated.csv

## Saving the validation report separatley

In [60]:
validation_report_path = "../data/cleaned_data/APL_Day2_Validation_Report.csv"

validation_report.to_csv(
    validation_report_path,
    index=False,
    encoding="utf-8"
)

print("Validation report saved successfully.")
print(validation_report_path)

Validation report saved successfully.
../data/cleaned_data/APL_Day2_Validation_Report.csv